services:
  db:
    image: postgres:16
    container_name: caja_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caja
    ports:
      - "5432:5432"
    volumes:
      - caja_pgdata:/var/lib/postgresql/data

volumes:
  caja_pgdata:
